INSERT INTO Status_Codes (status_code, status_title) VALUES ('N', "Not Learned");
INSERT INTO Status_Codes (status_code, status_title) VALUES ('P', "In Progress");
INSERT INTO Status_Codes (status_code, status_title) VALUES ('L', "Learned");
INSERT INTO All_Languages (language_id, language_name) VALUES ('af', 'Afrikaans');
INSERT INTO All_Languages (language_id, language_name) VALUES ('sq', 'Albanian');
INSERT INTO All_Languages (language_id, language_name) VALUES ('am', 'Amharic');
INSERT INTO All_Languages (language_id, language_name) VALUES ('ar', 'Arabic');
INSERT INTO All_Languages (language_id, language_name) VALUES ('hy', 'Armenian');
INSERT INTO All_Languages (language_id, language_name) VALUES ('az', 'Azerbaijani');
INSERT INTO All_Languages (language_id, language_name) VALUES ('eu', 'Basque');
INSERT INTO All_Languages (language_id, language_name) VALUES ('be', 'Belarusian');
INSERT INTO All_Languages (language_id, language_name) VALUES ('bn', 'Bengali');
INSERT INTO All_Languages (language_id, language_name) VALUES ('bs', 'Bosnian');
INSERT INTO All_Languages (language_id, language_name) VALUES ('bg', 'Bulgarian');
INSERT INTO All_Languages (language_id, language_name) VALUES ('ca', 'Catalan');
INSERT INTO All_Languages (language_id, language_name) VALUES ('ceb', 'Cebuano');
INSERT INTO All_Languages (language_id, language_name) VALUES ('ny', 'Chichewa');
INSERT INTO All_Languages (language_id, language_name) VALUES ('zh-CN', 'Chinese (Simplified)');
INSERT INTO All_Languages (language_id, language_name) VALUES ('zh-TW', 'Chinese (Traditional)');
INSERT INTO All_Languages (language_id, language_name) VALUES ('co', 'Corsican');
INSERT INTO All_Languages (language_id, language_name) VALUES ('hr', 'Croatian');
INSERT INTO All_Languages (language_id, language_name) VALUES ('cs', 'Czech');
INSERT INTO All_Languages (language_id, language_name) VALUES ('da', 'Danish');
INSERT INTO All_Languages (language_id, language_name) VALUES ('en', 'English');
INSERT INTO All_Languages (language_id, language_name) VALUES ('eo', 'Esperanto');
INSERT INTO All_Languages (language_id, language_name) VALUES ('et', 'Estonian');
INSERT INTO All_Languages (language_id, language_name) VALUES ('tl', 'Filipino');
INSERT INTO All_Languages (language_id, language_name) VALUES ('fi', 'Finnish');
INSERT INTO All_Languages (language_id, language_name) VALUES ('fr', 'French');
INSERT INTO All_Languages (language_id, language_name) VALUES ('fy', 'Frisian');
INSERT INTO All_Languages (language_id, language_name) VALUES ('gl', 'Galician');
INSERT INTO All_Languages (language_id, language_name) VALUES ('ka', 'Georgian');
INSERT INTO All_Languages (language_id, language_name) VALUES ('de', 'German');
INSERT INTO All_Languages (language_id, language_name) VALUES ('el', 'Greek');
INSERT INTO All_Languages (language_id, language_name) VALUES ('gu', 'Gujaranti');
INSERT INTO All_Languages (language_id, language_name) VALUES ('ht', 'Haitian Creole');
INSERT INTO All_Languages (language_id, language_name) VALUES ('ha', 'Hausa');
INSERT INTO All_Languages (language_id, language_name) VALUES ('haw', 'Hawaiian');
INSERT INTO All_Languages (language_id, language_name) VALUES ('iw', 'Hebrew');
INSERT INTO All_Languages (language_id, language_name) VALUES ('hi', 'Hindi');
INSERT INTO All_Languages (language_id, language_name) VALUES ('hmn', 'Hmong');
INSERT INTO All_Languages (language_id, language_name) VALUES ('hu', 'Hungarian');
INSERT INTO All_Languages (language_id, language_name) VALUES ('is', 'Icelandic');
INSERT INTO All_Languages (language_id, language_name) VALUES ('ig', 'Igbo');
INSERT INTO All_Languages (language_id, language_name) VALUES ('id', 'Indonesian');
INSERT INTO All_Languages (language_id, language_name) VALUES ('ga', 'Irish');
INSERT INTO All_Languages (language_id, language_name) VALUES ('it', 'Italian');
INSERT INTO All_Languages (language_id, language_name) VALUES ('ja', 'Japanese');
INSERT INTO All_Languages (language_id, language_name) VALUES ('jw', 'Javanese');
INSERT INTO All_Languages (language_id, language_name) VALUES ('kn', 'Kannada');
INSERT INTO All_Languages (language_id, language_name) VALUES ('kk', 'Kazakh');
INSERT INTO All_Languages (language_id, language_name) VALUES ('km', 'Khmer');
INSERT INTO All_Languages (language_id, language_name) VALUES ('rw', 'Kinyarwanda');
INSERT INTO All_Languages (language_id, language_name) VALUES ('ko', 'Korean');
INSERT INTO All_Languages (language_id, language_name) VALUES ('ku', 'Kurdish (Kurmanji)');
INSERT INTO All_Languages (language_id, language_name) VALUES ('ky', 'Kyrgyz');
INSERT INTO All_Languages (language_id, language_name) VALUES ('lo', 'Lao');
INSERT INTO All_Languages (language_id, language_name) VALUES ('la', 'Latin');
INSERT INTO All_Languages (language_id, language_name) VALUES ('lv', 'Latvian');
INSERT INTO All_Languages (language_id, language_name) VALUES ('lt', 'Lithuanian');
INSERT INTO All_Languages (language_id, language_name) VALUES ('lb', 'Luxembourgish');
INSERT INTO All_Languages (language_id, language_name) VALUES ('mk', 'Macedonian');
INSERT INTO All_Languages (language_id, language_name) VALUES ('mg', 'Malagasy');
INSERT INTO All_Languages (language_id, language_name) VALUES ('ms', 'Malay');
INSERT INTO All_Languages (language_id, language_name) VALUES ('ml', 'Malayalam');
INSERT INTO All_Languages (language_id, language_name) VALUES ('mt', 'Maltese');
INSERT INTO All_Languages (language_id, language_name) VALUES ('mi', 'Maori');
INSERT INTO All_Languages (language_id, language_name) VALUES ('mr', 'Marathi');
INSERT INTO All_Languages (language_id, language_name) VALUES ('mn', 'Mongolian');
INSERT INTO All_Languages (language_id, language_name) VALUES ('my', 'Myanmar (Burmese'));
INSERT INTO All_Languages (language_id, language_name) VALUES ('ne', 'Nepali');
INSERT INTO All_Languages (language_id, language_name) VALUES ('no', 'Norwegian');
INSERT INTO All_Languages (language_id, language_name) VALUES ('or', 'Odia (Oriya)');
INSERT INTO All_Languages (language_id, language_name) VALUES ('ps', 'Pashto');
INSERT INTO All_Languages (language_id, language_name) VALUES ('fa', 'Persian');
INSERT INTO All_Languages (language_id, language_name) VALUES ('pl', 'Polish');
INSERT INTO All_Languages (language_id, language_name) VALUES ('pt', 'Portuguese');
INSERT INTO All_Languages (language_id, language_name) VALUES ('pa', 'Punjabi');
INSERT INTO All_Languages (language_id, language_name) VALUES ('ro', 'Romanian');
INSERT INTO All_Languages (language_id, language_name) VALUES ('ru', 'Russian');
INSERT INTO All_Languages (language_id, language_name) VALUES ('sm', 'Samoan');
INSERT INTO All_Languages (language_id, language_name) VALUES ('gd', 'Scots Gaelic');
INSERT INTO All_Languages (language_id, language_name) VALUES ('sr', 'Serbian');
INSERT INTO All_Languages (language_id, language_name) VALUES ('st', 'Sesotho');
INSERT INTO All_Languages (language_id, language_name) VALUES ('sn', 'Shona');
INSERT INTO All_Languages (language_id, language_name) VALUES ('sd', 'Sindhi');
INSERT INTO All_Languages (language_id, language_name) VALUES ('si', 'Sinhzala');
INSERT INTO All_Languages (language_id, language_name) VALUES ('sk', 'Slovak');
INSERT INTO All_Languages (language_id, language_name) VALUES ('sl', 'Slovenian');
INSERT INTO All_Languages (language_id, language_name) VALUES ('so', 'Somali');
INSERT INTO All_Languages (language_id, language_name) VALUES ('es', 'Spanish');
INSERT INTO All_Languages (language_id, language_name) VALUES ('su', 'Sudanese');
INSERT INTO All_Languages (language_id, language_name) VALUES ('sw', 'Swahili');
INSERT INTO All_Languages (language_id, language_name) VALUES ('sv', 'Swedish');
INSERT INTO All_Languages (language_id, language_name) VALUES ('tg', 'Tajik');
INSERT INTO All_Languages (language_id, language_name) VALUES ('ta', 'Tamil');
INSERT INTO All_Languages (language_id, language_name) VALUES ('tt', 'Tatar');
INSERT INTO All_Languages (language_id, language_name) VALUES ('te', 'Telugu');
INSERT INTO All_Languages (language_id, language_name) VALUES ('th', 'Thai');
INSERT INTO All_Languages (language_id, language_name) VALUES ('tr', 'Turkish');
INSERT INTO All_Languages (language_id, language_name) VALUES ('tk', 'Turkmen');
INSERT INTO All_Languages (language_id, language_name) VALUES ('uk', 'Ukrainian');
INSERT INTO All_Languages (language_id, language_name) VALUES ('ur', 'Urdu');
INSERT INTO All_Languages (language_id, language_name) VALUES ('ug', 'Uyghur');
INSERT INTO All_Languages (language_id, language_name) VALUES ('uz', 'Uzbek');
INSERT INTO All_Languages (language_id, language_name) VALUES ('vi', 'Vietnamese');
INSERT INTO All_Languages (language_id, language_name) VALUES ('cy', 'Welsh');
INSERT INTO All_Languages (language_id, language_name) VALUES ('xh', 'Xhosa');
INSERT INTO All_Languages (language_id, language_name) VALUES ('yi', 'Yiddish');
INSERT INTO All_Languages (language_id, language_name) VALUES ('yo', 'Yoruba');
INSERT INTO All_Languages (language_id, language_name) VALUES ('zu', 'Zulu');
INSERT INTO All_Languages (language_id, language_name) VALUES ('he', 'Hebrew');
INSERT INTO All_Languages (language_id, language_name) VALUES ('zh', 'Chinese (Simplified)');
INSERT INTO Categories (category_id, category_name) VALUES (1, "Colors");
INSERT INTO Categories (category_id, category_name) VALUES (2, "Numbers 1-10");
INSERT INTO Categories (category_id, category_name) VALUES (3, "Numbers (tens)");
INSERT INTO Categories (category_id, category_name) VALUES (4, "Numbers (greater than 100)");
INSERT INTO Categories (category_id, category_name) VALUES (5, "Food Adjectives");
INSERT INTO Categories (category_id, category_name) VALUES (6, "Parts of the House");
INSERT INTO Categories (category_id, category_name) VALUES (7, "Furniture");
